package libXray

fun interface DialerController {
    fun protectFd(fileDescriptor: Int): Boolean
}

/** Contract fixture matching the gomobile surface generated by XTLS/libXray v26.7.28. */
class LibXray private constructor() {
    companion object {
        var observedRequest: String? = null
            private set
        var observedDns: String? = null
            private set
        var dnsReset: Boolean = false
            private set
        private var controller: DialerController? = null
        var simulateStoppedAfterStart: Boolean = false
        private var coreRunning: Boolean = false
        private val dialerControllers = mutableListOf<DialerController>()
        val registrationCount: Int get() = dialerControllers.size

        @JvmStatic
        fun registerDialerController(value: DialerController) {
            controller = value
            dialerControllers += value
        }

        @JvmStatic
        fun setDNS(value: DialerController, server: String) {
            controller = value
            observedDns = server
        }

        @JvmStatic
        fun resetDNS() {
            dnsReset = true
        }

        @JvmStatic
        fun invoke(request: String): String {
            if (request.contains("\"method\":\"getXrayState\"")) {
                return "{\"success\":true,\"data\":{\"running\":$coreRunning}}"
            }
            observedRequest = request
            if (request.contains("\"method\":\"runXrayFromJson\"")) {
                coreRunning = !simulateStoppedAfterStart
            }
            if (request.contains("\"method\":\"stopXray\"")) coreRunning = false
            return "{\"success\":true,\"data\":{}}"
        }

        fun protect(fileDescriptor: Int): Boolean =
            dialerControllers.isNotEmpty() && dialerControllers.all { it.protectFd(fileDescriptor) }

        fun resetObservations() {
            observedRequest = null
            observedDns = null
            dnsReset = false
            simulateStoppedAfterStart = false
            coreRunning = false
        }
    }
}
