package libXray

fun interface DialerController {
    fun protectFd(fileDescriptor: Int): Boolean
}

/** Contract fixture matching the gomobile surface generated by XTLS/libXray v26.7.28. */
class LibXray private constructor() {
    companion object {
        var observedRequest: String? = null
            private set
        var observedDns: String? = null
            private set
        var dnsReset: Boolean = false
            private set
        var boundTunFd: Int? = null
            private set
        var tunReset: Boolean = false
            private set
        private var controller: DialerController? = null

        @JvmStatic
        fun setTunFd(fd: Int) {
            require(fd >= 0)
            boundTunFd = fd
        }

        @JvmStatic
        fun resetTunFd() {
            boundTunFd = null
            tunReset = true
        }

        @JvmStatic
        fun registerDialerController(value: DialerController) {
            controller = value
        }

        @JvmStatic
        fun setDNS(value: DialerController, server: String) {
            controller = value
            observedDns = server
        }

        @JvmStatic
        fun resetDNS() {
            dnsReset = true
        }

        @JvmStatic
        fun invoke(request: String): String {
            observedRequest = request
            return "{\"success\":true,\"data\":{}}"
        }

        fun protect(fileDescriptor: Int): Boolean = controller?.protectFd(fileDescriptor) == true

        fun resetObservations() {
            observedRequest = null
            observedDns = null
            dnsReset = false
            boundTunFd = null
            tunReset = false
            controller = null
        }
    }
}
