-- Ganj VPN Super App — PostgreSQL baseline schema
-- Phase 0 contract. Production migrations are generated by the backend project.

BEGIN;

CREATE TABLE users (
    id uuid PRIMARY KEY,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','blocked','deleted')),
    display_name text,
    locale varchar(16) NOT NULL DEFAULT 'fa-IR',
    timezone varchar(64) NOT NULL DEFAULT 'Asia/Tehran',
    risk_level text NOT NULL DEFAULT 'normal' CHECK (risk_level IN ('normal','elevated','restricted')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE user_identities (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider text NOT NULL CHECK (provider IN ('guest','telegram','google_play','admin')),
    provider_subject varchar(255) NOT NULL,
    username text,
    profile jsonb NOT NULL DEFAULT '{}'::jsonb,
    verified_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider, provider_subject)
);

CREATE TABLE devices (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform text NOT NULL CHECK (platform IN ('android','ios','web','bot')),
    public_key bytea,
    key_attestation jsonb,
    app_version varchar(32),
    os_version varchar(32),
    device_class varchar(64),
    integrity_state text NOT NULL DEFAULT 'unknown',
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','revoked')),
    last_seen_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz
);
CREATE INDEX devices_user_status_idx ON devices(user_id, status);

CREATE TABLE auth_sessions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    token_family_id uuid NOT NULL,
    refresh_token_hash bytea NOT NULL UNIQUE,
    scopes text[] NOT NULL DEFAULT ARRAY[]::text[],
    expires_at timestamptz NOT NULL,
    last_used_at timestamptz,
    revoked_at timestamptz,
    revoke_reason text,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_sessions_user_active_idx ON auth_sessions(user_id, expires_at) WHERE revoked_at IS NULL;
CREATE INDEX auth_sessions_family_idx ON auth_sessions(token_family_id);

CREATE TABLE auth_challenges (
    id uuid PRIMARY KEY,
    kind text NOT NULL CHECK (kind IN ('telegram_oidc','telegram_bot_link','device_proof')),
    challenge_hash bytea NOT NULL UNIQUE,
    user_id uuid REFERENCES users(id) ON DELETE CASCADE,
    device_id uuid REFERENCES devices(id) ON DELETE CASCADE,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE plans (
    id uuid PRIMARY KEY,
    code varchar(64) NOT NULL UNIQUE,
    name text NOT NULL,
    tier text NOT NULL CHECK (tier IN ('free','premium','vip')),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('draft','active','archived')),
    device_limit integer NOT NULL DEFAULT 1 CHECK (device_limit > 0),
    traffic_limit_bytes bigint CHECK (traffic_limit_bytes IS NULL OR traffic_limit_bytes >= 0),
    duration_days integer CHECK (duration_days IS NULL OR duration_days > 0),
    speed_limit_kbps integer CHECK (speed_limit_kbps IS NULL OR speed_limit_kbps > 0),
    features jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE plan_prices (
    id uuid PRIMARY KEY,
    plan_id uuid NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
    channel text NOT NULL CHECK (channel IN ('play','direct','telegram','admin')),
    currency char(3) NOT NULL,
    amount_minor bigint NOT NULL CHECK (amount_minor >= 0),
    external_product_id varchar(255),
    region varchar(8),
    active_from timestamptz NOT NULL DEFAULT now(),
    active_until timestamptz,
    UNIQUE (plan_id, channel, currency, region, active_from)
);

CREATE TABLE subscriptions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id),
    plan_id uuid NOT NULL REFERENCES plans(id),
    status text NOT NULL CHECK (status IN ('pending','active','grace','hold','cancelled','expired','revoked')),
    purchase_channel text NOT NULL CHECK (purchase_channel IN ('free','play','direct','telegram','wallet','admin')),
    starts_at timestamptz NOT NULL,
    ends_at timestamptz,
    auto_renew boolean NOT NULL DEFAULT false,
    external_reference varchar(255),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX subscriptions_user_status_idx ON subscriptions(user_id, status, ends_at);

CREATE TABLE services (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id),
    subscription_id uuid REFERENCES subscriptions(id),
    name text NOT NULL,
    status text NOT NULL CHECK (status IN ('pending','active','disabled','expired','revoked','deleted')),
    provider_kind varchar(64),
    external_service_id varchar(255),
    traffic_limit_bytes bigint,
    traffic_used_bytes bigint NOT NULL DEFAULT 0 CHECK (traffic_used_bytes >= 0),
    starts_at timestamptz,
    expires_at timestamptz,
    config_version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider_kind, external_service_id)
);
CREATE INDEX services_user_status_idx ON services(user_id, status, expires_at);

CREATE TABLE service_entitlements (
    service_id uuid PRIMARY KEY REFERENCES services(id) ON DELETE CASCADE,
    allowed_tiers text[] NOT NULL DEFAULT ARRAY['free']::text[],
    allowed_protocols text[] NOT NULL DEFAULT ARRAY['vless']::text[],
    device_limit integer NOT NULL DEFAULT 1 CHECK (device_limit > 0),
    region_allowlist text[],
    region_denylist text[],
    policy jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE provider_connections (
    id uuid PRIMARY KEY,
    kind varchar(64) NOT NULL,
    name text NOT NULL,
    base_url text NOT NULL,
    secret_reference text NOT NULL,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled','degraded')),
    capabilities jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE vpn_servers (
    id uuid PRIMARY KEY,
    provider_connection_id uuid REFERENCES provider_connections(id),
    code varchar(64) NOT NULL UNIQUE,
    name text NOT NULL,
    country_code char(2) NOT NULL,
    city text,
    tier text NOT NULL CHECK (tier IN ('free','premium','vip')),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','draining','disabled','maintenance')),
    capacity integer NOT NULL DEFAULT 0 CHECK (capacity >= 0),
    active_users integer NOT NULL DEFAULT 0 CHECK (active_users >= 0),
    weight numeric(6,3) NOT NULL DEFAULT 1,
    tags text[] NOT NULL DEFAULT ARRAY[]::text[],
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX vpn_servers_discovery_idx ON vpn_servers(status, tier, country_code);

CREATE TABLE server_endpoints (
    id uuid PRIMARY KEY,
    server_id uuid NOT NULL REFERENCES vpn_servers(id) ON DELETE CASCADE,
    protocol text NOT NULL CHECK (protocol IN ('vless','vmess','trojan','shadowsocks','wireguard')),
    transport text NOT NULL,
    security text,
    public_host text NOT NULL,
    public_port integer NOT NULL CHECK (public_port BETWEEN 1 AND 65535),
    secret_reference text NOT NULL,
    priority integer NOT NULL DEFAULT 100,
    enabled boolean NOT NULL DEFAULT true,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX server_endpoints_server_enabled_idx ON server_endpoints(server_id, enabled, priority);

CREATE TABLE server_health_samples (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    server_id uuid NOT NULL REFERENCES vpn_servers(id) ON DELETE CASCADE,
    source_region varchar(16),
    latency_ms integer,
    packet_success numeric(5,4),
    jitter_ms integer,
    load_ratio numeric(5,4),
    success boolean NOT NULL,
    sampled_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX server_health_recent_idx ON server_health_samples(server_id, sampled_at DESC);

CREATE TABLE config_envelopes (
    id uuid PRIMARY KEY,
    service_id uuid NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    server_id uuid NOT NULL REFERENCES vpn_servers(id),
    key_version varchar(64) NOT NULL,
    ciphertext bytea NOT NULL,
    nonce bytea NOT NULL,
    profile_version bigint NOT NULL,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX config_envelopes_lookup_idx ON config_envelopes(service_id, device_id, expires_at);

CREATE TABLE connection_sessions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id),
    device_id uuid NOT NULL REFERENCES devices(id),
    service_id uuid NOT NULL REFERENCES services(id),
    server_id uuid NOT NULL REFERENCES vpn_servers(id),
    protocol text NOT NULL,
    status text NOT NULL CHECK (status IN ('connecting','connected','ended','failed')),
    started_at timestamptz NOT NULL,
    connected_at timestamptz,
    ended_at timestamptz,
    bytes_up bigint NOT NULL DEFAULT 0 CHECK (bytes_up >= 0),
    bytes_down bigint NOT NULL DEFAULT 0 CHECK (bytes_down >= 0),
    error_code varchar(64),
    app_version varchar(32)
);
CREATE INDEX connection_sessions_user_recent_idx ON connection_sessions(user_id, started_at DESC);
CREATE INDEX connection_sessions_server_active_idx ON connection_sessions(server_id, status) WHERE ended_at IS NULL;

CREATE TABLE usage_counters (
    service_id uuid NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    period_start timestamptz NOT NULL,
    period_end timestamptz NOT NULL,
    bytes_up bigint NOT NULL DEFAULT 0 CHECK (bytes_up >= 0),
    bytes_down bigint NOT NULL DEFAULT 0 CHECK (bytes_down >= 0),
    source_sequence bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (service_id, period_start)
);

CREATE TABLE wallet_accounts (
    id uuid PRIMARY KEY,
    user_id uuid REFERENCES users(id),
    system_code varchar(64),
    currency char(3) NOT NULL,
    account_type text NOT NULL CHECK (account_type IN ('asset','liability','revenue','expense','clearing')),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','frozen','closed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((user_id IS NOT NULL) <> (system_code IS NOT NULL)),
    UNIQUE (user_id, currency),
    UNIQUE (system_code, currency)
);

CREATE TABLE wallet_transactions (
    id uuid PRIMARY KEY,
    business_key varchar(255) NOT NULL UNIQUE,
    kind text NOT NULL CHECK (kind IN ('charge','purchase','refund','adjustment','bonus','transfer')),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','posted','reversed')),
    description text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    posted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE wallet_entries (
    id uuid PRIMARY KEY,
    transaction_id uuid NOT NULL REFERENCES wallet_transactions(id),
    account_id uuid NOT NULL REFERENCES wallet_accounts(id),
    amount_minor bigint NOT NULL CHECK (amount_minor <> 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (transaction_id, account_id, amount_minor)
);
CREATE INDEX wallet_entries_account_idx ON wallet_entries(account_id, created_at DESC);

CREATE TABLE orders (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id),
    status text NOT NULL CHECK (status IN ('pending','authorized','paid','fulfilled','cancelled','refunded','failed')),
    channel text NOT NULL CHECK (channel IN ('play','direct','telegram','wallet','admin')),
    currency char(3) NOT NULL,
    total_minor bigint NOT NULL CHECK (total_minor >= 0),
    idempotency_key varchar(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, idempotency_key)
);

CREATE TABLE order_items (
    id uuid PRIMARY KEY,
    order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    plan_id uuid REFERENCES plans(id),
    service_id uuid REFERENCES services(id),
    quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_amount_minor bigint NOT NULL CHECK (unit_amount_minor >= 0),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE payments (
    id uuid PRIMARY KEY,
    order_id uuid NOT NULL REFERENCES orders(id),
    provider varchar(64) NOT NULL,
    provider_reference varchar(255),
    status text NOT NULL CHECK (status IN ('pending','authorized','paid','failed','cancelled','refunded')),
    amount_minor bigint NOT NULL CHECK (amount_minor >= 0),
    currency char(3) NOT NULL,
    verified_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider, provider_reference)
);

CREATE TABLE refunds (
    id uuid PRIMARY KEY,
    payment_id uuid NOT NULL REFERENCES payments(id),
    provider_reference varchar(255),
    amount_minor bigint NOT NULL CHECK (amount_minor > 0),
    status text NOT NULL CHECK (status IN ('pending','completed','failed')),
    reason text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE play_purchases (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id),
    order_id uuid REFERENCES orders(id),
    package_name varchar(255) NOT NULL,
    product_id varchar(255) NOT NULL,
    purchase_token_hash bytea NOT NULL UNIQUE,
    purchase_state text NOT NULL,
    entitlement_state text NOT NULL,
    acknowledged_at timestamptz,
    expires_at timestamptz,
    last_verified_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE push_tokens (
    id uuid PRIMARY KEY,
    device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    provider text NOT NULL CHECK (provider IN ('fcm','apns')),
    token_ciphertext bytea NOT NULL,
    token_hash bytea NOT NULL UNIQUE,
    locale varchar(16),
    enabled boolean NOT NULL DEFAULT true,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind varchar(64) NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    action jsonb,
    read_at timestamptz,
    expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX notifications_user_unread_idx ON notifications(user_id, created_at DESC) WHERE read_at IS NULL;

CREATE TABLE campaigns (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    kind text NOT NULL CHECK (kind IN ('banner','popup','announcement','push')),
    status text NOT NULL CHECK (status IN ('draft','scheduled','running','paused','completed','cancelled')),
    starts_at timestamptz,
    ends_at timestamptz,
    frequency_cap jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by uuid REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE campaign_audiences (
    id uuid PRIMARY KEY,
    campaign_id uuid NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    rule jsonb NOT NULL,
    estimated_size bigint,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE campaign_creatives (
    id uuid PRIMARY KEY,
    campaign_id uuid NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    locale varchar(16) NOT NULL,
    title text NOT NULL,
    body text,
    media_url text,
    action jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (campaign_id, locale)
);

CREATE TABLE notification_deliveries (
    id uuid PRIMARY KEY,
    campaign_id uuid REFERENCES campaigns(id) ON DELETE CASCADE,
    notification_id uuid REFERENCES notifications(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id uuid REFERENCES devices(id) ON DELETE SET NULL,
    channel text NOT NULL CHECK (channel IN ('in_app','push','telegram')),
    status text NOT NULL CHECK (status IN ('queued','sent','delivered','opened','failed','suppressed')),
    provider_message_id varchar(255),
    failure_code varchar(64),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX notification_deliveries_campaign_idx ON notification_deliveries(campaign_id, status);

CREATE TABLE user_consents (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    purpose varchar(64) NOT NULL,
    granted boolean NOT NULL,
    policy_version varchar(32) NOT NULL,
    source text NOT NULL,
    recorded_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX user_consents_latest_idx ON user_consents(user_id, purpose, recorded_at DESC);

CREATE TABLE idempotency_keys (
    id uuid PRIMARY KEY,
    subject_id uuid NOT NULL,
    endpoint varchar(255) NOT NULL,
    key varchar(255) NOT NULL,
    request_hash bytea NOT NULL,
    response_status integer,
    response_body jsonb,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (subject_id, endpoint, key)
);

CREATE TABLE outbox_events (
    id uuid PRIMARY KEY,
    aggregate_type varchar(64) NOT NULL,
    aggregate_id uuid NOT NULL,
    event_type varchar(128) NOT NULL,
    payload jsonb NOT NULL,
    available_at timestamptz NOT NULL DEFAULT now(),
    attempts integer NOT NULL DEFAULT 0,
    published_at timestamptz,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX outbox_pending_idx ON outbox_events(available_at, created_at) WHERE published_at IS NULL;

CREATE TABLE legacy_links (
    id uuid PRIMARY KEY,
    entity_type varchar(64) NOT NULL,
    new_id uuid NOT NULL,
    legacy_table varchar(64) NOT NULL,
    legacy_id varchar(255) NOT NULL,
    legacy_fingerprint bytea,
    synced_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (legacy_table, legacy_id),
    UNIQUE (entity_type, new_id)
);

CREATE TABLE audit_logs (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    actor_user_id uuid REFERENCES users(id),
    actor_type varchar(32) NOT NULL,
    action varchar(128) NOT NULL,
    target_type varchar(64),
    target_id varchar(255),
    request_id uuid,
    ip_prefix varchar(64),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_logs_target_idx ON audit_logs(target_type, target_id, occurred_at DESC);

CREATE TABLE security_events (
    id uuid PRIMARY KEY,
    user_id uuid REFERENCES users(id),
    device_id uuid REFERENCES devices(id),
    kind varchar(128) NOT NULL,
    severity text NOT NULL CHECK (severity IN ('info','low','medium','high','critical')),
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX security_events_recent_idx ON security_events(severity, occurred_at DESC);

COMMIT;

